# Generated by Django 4.2.6 on 2023-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_alter_profile_avatar_alter_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/123.png', upload_to='media/avatars'),
        ),
    ]
