# Generated by Django 4.2.6 on 2023-12-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='events_count',
            field=models.PositiveIntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prizes_count',
            field=models.PositiveIntegerField(default=123),
        ),
    ]
