# Generated by Django 4.2.6 on 2023-12-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_alter_profile_events_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='events_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prizes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
