# Generated by Django 4.2.6 on 2023-12-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_alter_profile_events_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
