# Generated by Django 4.2.6 on 2023-12-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg',
            field=models.CharField(default='@bot', max_length=32),
        ),
    ]
