# Generated by Django 4.2.6 on 2023-12-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0006_profile_tg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Moskva', max_length=50),
        ),
    ]
