# Generated by Django 4.2.6 on 2023-12-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_profile_age_eventreact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, choices=[('BACKEND', 'BACKEND'), ('UI/UX', 'UI'), ('Product manager', 'Product '), ('Project manager', 'Project '), ('Frontend', 'Frontend'), ('Fullstack', 'Fullstack'), ('Analyst', 'Analyst')], default='Fullstack', max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authy.event')),
            ],
        ),
    ]
