# Generated by Django 4.2.6 on 2023-12-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0008_remove_profile_proved_event_count_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_proved',
            field=models.BooleanField(default=False),
        ),
    ]
