# Generated by Django 4.2.6 on 2023-12-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0009_profile_is_proved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
