# Generated by Django 4.2.6 on 2023-12-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0010_event_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
