# Generated by Django 4.2.6 on 2023-12-16 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0011_alter_event_date_start_alter_eventtag_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=datetime.date(2023, 12, 9)),
        ),
    ]
