# Generated by Django 4.2.6 on 2023-12-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0012_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bday',
            field=models.DateTimeField(blank=True, default='2000-01-05'),
        ),
    ]
