# Generated by Django 4.2.6 on 2023-12-16 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0012_alter_event_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreact',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 13)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=datetime.date(2023, 12, 7)),
        ),
    ]
