# Generated by Django 4.2.6 on 2023-12-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0013_alter_profile_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bday',
            field=models.DateField(blank=True, default='2000-01-05'),
        ),
    ]
