# Generated by Django 4.2.6 on 2023-12-17 10:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0017_team_alter_event_date_start_alter_eventreact_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('beginner', 'beginner'), ('expirienced', 'expirienced'), ('fan', 'fan')], default='beginner', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=datetime.date(2023, 12, 9)),
        ),
        migrations.AlterField(
            model_name='eventreact',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 7)),
        ),
    ]
